name: Enologie
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2571
title: Enologie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe7db'
    - '#3c2922'
    - '#7a9a82'
    - '#000600'
    - '#aec762'
  brandStrength: 1
  lightness: 0.25
  saturation: 0.1875
  rhythmicContrast: 0.8636595443822443
purpose: []
