name: Enologie
favicon: null
layout_spectrum: 0.04045385913923383
typography_spectrum: 0.5181236371863633
title: Enologie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5737798835616559
  lightness: 0.3282417010050267
  saturation: 0.17741965176537633
  rhythmicContrast: 0.8636595443822443
purpose: []
