name: Enologie
favicon: null
layout_spectrum: 0
typography_spectrum: 0.2571
title: Enologie
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#602740'
    - '#834c6b'
    - '#c46591'
    - '#39050f'
    - '#bb507c'
  brandStrength: 0.5
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.8636595443822443
purpose: []
